# Generated by Django 4.1.1 on 2022-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddInstructorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_fname', models.CharField(max_length=255)),
                ('ins_lname', models.CharField(max_length=255)),
                ('ins_email', models.EmailField(max_length=255)),
                ('ins_phone', models.CharField(max_length=12)),
                ('ins_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_fname', models.CharField(max_length=255)),
                ('stu_lname', models.CharField(max_length=255)),
                ('stu_email', models.EmailField(max_length=255)),
                ('stu_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
        ),
    ]
