# Generated by Django 4.1.3 on 2022-12-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_fname', models.CharField(max_length=255)),
                ('stu_lname', models.CharField(max_length=255)),
                ('stu_email', models.EmailField(max_length=255)),
                ('stu_phone', models.CharField(max_length=12)),
                ('stu_dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_category', models.CharField(max_length=255)),
                ('course_difficulty', models.CharField(max_length=255)),
                ('total_lesson', models.IntegerField()),
                ('course_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrollStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('student_phone', models.CharField(max_length=255)),
                ('student_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_fname', models.CharField(max_length=255)),
                ('ins_lname', models.CharField(max_length=255)),
                ('ins_email', models.EmailField(max_length=255)),
                ('ins_phone', models.CharField(max_length=20)),
                ('ins_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('site_email', models.CharField(max_length=255)),
                ('site_copyright', models.CharField(max_length=255)),
                ('allow_registration', models.IntegerField()),
                ('main_website', models.CharField(max_length=255)),
                ('website_desc', models.TextField()),
                ('maintanance_mode', models.IntegerField()),
            ],
        ),
    ]
