# Generated by Django 4.1.1 on 2022-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_category', models.CharField(max_length=255)),
                ('course_difficulty', models.CharField(max_length=255)),
                ('total_lesson', models.IntegerField()),
                ('course_desc', models.TextField()),
            ],
        ),
    ]
