# Generated by Django 4.1.1 on 2022-12-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0003_adminmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('site_email', models.CharField(max_length=255)),
                ('site_copyright', models.CharField(max_length=255)),
                ('allow_registration', models.IntegerField()),
                ('main_website', models.CharField(max_length=255)),
                ('website_desc', models.TextField()),
                ('maintanance_mode', models.IntegerField()),
            ],
        ),
    ]
