# Generated by Django 4.1.3 on 2022-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0004_websettingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_fname', models.CharField(max_length=255)),
                ('ins_lname', models.CharField(max_length=255)),
                ('ins_email', models.EmailField(max_length=255)),
                ('ins_phone', models.CharField(max_length=20)),
                ('ins_desc', models.TextField()),
            ],
        ),
    ]
