# Generated by Django 4.1.3 on 2022-12-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0005_instructormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('student_phone', models.CharField(max_length=255)),
                ('student_email', models.CharField(max_length=255)),
            ],
        ),
    ]
